name: Deploying to Firebase

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing firebase 
      run: npm install -g firebase-tools
    - name: Deploying
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
